# -*- encoding: utf-8 -*-

require 'aliyun/common'
require 'aliyun/oss/util'
require 'aliyun/oss/exception'
require 'aliyun/oss/struct'
require 'aliyun/oss/config'
require 'aliyun/oss/http'
require 'aliyun/oss/protocol'
require 'aliyun/oss/multipart'
require 'aliyun/oss/upload'
require 'aliyun/oss/download'
require 'aliyun/oss/iterator'
require 'aliyun/oss/object'
require 'aliyun/oss/bucket'
require 'aliyun/oss/client'
